Page({
  
  data:{
    dataList:[
      {
        'date':'2022.09',
        'part':'方案拟定',
        'content':'团队召开帮扶南华的会议，联合专家共同研讨教育振兴南华的可行性方案',
        'image':'https://pic1.imgdb.cn/item/67eff4aa0ba3d5a1d7ed6348.png' // 示例图片路径
      },
      {
        'date':'2023.07',
        'part':'支教团成立',
        'content':'疫情过后，为了将更优质的教育资源带去南华，团队成立了首个“研支团”，前往南华进行线下支教并调研',
        'image':'https://pic1.imgdb.cn/item/67eff7940ba3d5a1d7ed64d7.jpg'
      },
      {
        'date':'2024.03',
        'part':'云端伴读',
        'content':'发展云端伴读模式，支教志愿者们不但担任学生们的课程辅导教师，同时担任生活辅导员，对孩子们日常心理问题进行疏导。开展历史宣讲、知识竞答、红色故事进家门等活动，打造了主题文化课并进行展演',
        'image':'https://pic1.imgdb.cn/item/67eff6080ba3d5a1d7ed63fa.jpg'
      },
      {
        'date':'2025.01',
        'part':'打造“历史+文化+旅游”基地',
        'content':'提供“红军长征过沙桥”主题纪念馆设计方案。纪念馆展厅三维图示已经提交至当地政府。规划建立贯穿整个南华县的红色文旅路线。设计线上VR博物纪念馆6座。打造原创红色桌游4种，千余师生体验。',
        'image':'https://pic1.imgdb.cn/item/67ef7f730ba3d5a1d7ecd404.png'
      },
      {
        'date':'至今',
        'part':'实践成果',
        'content':'实践成果获人民网、央视新闻网、北京青年报、中国青年报、中国网、新华网等78家媒体报道，累计浏览量超70万',
        'image':'https://pic1.imgdb.cn/item/67eff71b0ba3d5a1d7ed649a.png'
      },
    ],
  },
})
